feat: add messenger/ courier + visitor/ trespasser from forum mafia
r3ndd/BeyondMafia-Integration pull request #342
Opened 2023-02-24 20:31 UTC by R9H9

I added Messenger and Courier, the Village and Mafia versions of Mailman from Forum Mafia, as well as Visitor.

2023-02-25 07:11 UTC, pikulet requested changes
this is good to me

some target adjustments might be good depending on what you feel is a good mechanic

(impt) visit should exclude self, description says "another player"
(optional) trespasser can exclude mafia 
(optional) messageSender can exclude self (able to fake reports on self)
(optional) courier can exclude mafia

2023-02-25 09:28 UTC, pikulet submitted a review, later dismissed

2023-02-25 10:28 UTC, pikulet approved these changes

2023-02-26 06:18 UTC, pikulet approved these changes

2023-02-26 21:12 UTC, starryburst approved these changes

2023-02-26 21:13 UTC, merged